import tkinter as tk
from tkinter import ttk
from PIL import Image, ImageTk
import re


def save_data():
    Name = ['Golden Apple', 'Palm Fruit', 'Hylian Tomato', 'Apple', 'Wildberry', 'Voltfruit', 'Fleet-Lotus Seeds',
            'Hydromelon', 'Mighty Bananas', 'Spicy Pepper', 'Fire Fruit', 'Ice Fruit', 'Shock Fruit', 'Splash Fruit',
            'Dazzlefruit', 'Bomb Flower', 'Puffshroom', 'Muddle Bud', 'Big Hearty Truffle', 'Hearty Truffle',
            'Endura Shroom', 'Rushroom', 'Brightcap', 'Stamella Shroom', 'Chillshroom', 'Sunshroom', 'Hylian Shroom',
            'Zapshroom', 'Silent Shroom', 'Razorshroom', 'Ironshroom', 'Skyshroom', 'Big Hearty Radish',
            'Hearty Radish', 'Endura Carrot', 'Hyrule Herb', 'Silent Princess', 'Fortified Pumpkin', 'Sun Pumpkin',
            'Swift Carrot', 'Stambulb', 'Korok Frond', 'Cool Safflina', 'Warm Safflina', 'Mighty Thistle', 'Armoranth',
            'Blue Nightshade', 'Electric Safflina', 'Swift Violet', 'Sundelion', 'Raw Gourmet Meat', 'Raw Whole Bird',
            'Raw Prime Meat', 'Raw Bird Thigh', 'Raw Meat', 'Raw Bird Drumstick', 'Courser Bee Honey', 'Hylian Rice',
            'Bird Egg', 'Tabantha Wheat', 'Hateno Cheese', 'Fresh Milk', 'Acorn', 'Chickaloo Tree Nut', 'Cane Sugar',
            'Goron Spice', 'Goat Butter', 'Monster Extract', 'Oil Jar', 'Dark Clump', 'Rock Salt', 'Star Fragment',
            'Hearty Salmon', 'Hearty Bass', 'Hyrule Bass', 'Staminoka Bass', 'Chillfin Trout', 'Sizzlefin Trout',
            'Voltfin Trout', 'Stealthfin Trout', 'Mighty Carp', 'Armored Carp', 'Sanke Carp', 'Ancient Arowana',
            'Glowing Cave Fish', 'Mighty Porgy', 'Armored Porgy', 'Sneaky River Snail', 'Razorclaw Crab',
            'Ironshell Crab', 'Bright-Eyed Crab', 'Fairy', 'Winterwing Butterfly', 'Summerwing Butterfly',
            'Thunderwing Butterfly', 'Smotherwing Butterfly', 'Cold Darner', 'Warm Darner', 'Electric Darner',
            'Energetic Rhino Beetle', 'Bladed Rhino Beetle', 'Rugged Rhino Beetle', 'Sunset Firefly', 'Deep Firefly',
            'Restless Cricket', 'Tireless Frog', 'Hot-Footed Frog', 'Sticky Frog', 'Hearty Lizard', 'Hightail Lizard',
            'Fireproof Lizard', 'Sticky Lizard', 'Diamond', 'Ruby', 'Sapphire', 'Topaz', 'Opal', 'Amber',
            'Luminous Stone', 'Flint', 'Bokoblin Guts', 'Moblin Guts', 'Horriblin Guts', 'Gibdo Guts',
            'Boss Bokoblin Guts', 'Lynel Guts', 'Gleeok Guts', 'Frox Guts', 'Molduga Guts', 'Hinox Guts',
            'Red Chuchu Jelly', 'White Chuchu Jelly', 'Yellow Chuchu Jelly', 'Chuchu Jelly', 'Octo Balloon',
            'Keese Eyeball', 'Fire Keese Eyeball', 'Ice Keese Eyeball', 'Electric Keese Eyeball', 'Octorok Eyeball',
            'Aerocuda Eyeball', 'Keese Wing', 'Fire Keese Wing', 'Ice Keese Wing', 'Electric Keese Wing',
            'Aerocuda Wing', 'Gibdo Wing', 'Gleeok Wing', 'Molduga Fin', 'Bokoblin Horn', 'Blue Bokoblin Horn',
            'Black Bokoblin Horn', 'Silver Bokoblin Horn', 'Boss Bokoblin Horn', 'Blue Boss Bokoblin Horn',
            'Black Boss Bokoblin Horn', 'Silver Boss Bokoblin Horn', 'Lizalfos Horn', 'Blue Lizalfos Horn',
            'Black Lizalfos Horn', 'Silver Lizalfos Horn', 'Fire-Breath Lizalfos Horn', 'Ice-Breath Lizalfos Horn',
            'Electric Lizalfos Horn', 'Lynel Saber Horn', 'Blue-Maned Lynel Saber Horn', 'White-Maned Lynel Saber Horn',
            'Silver Lynel Saber Horn', 'Soldier Construct Horn', 'Soldier Construct II Horn',
            'Soldier Construct III Horn', 'Soldier Construct IV Horn', 'Captain Construct I Horn',
            'Captain Construct II Horn', 'Captain Construct III Horn', 'Captain Construct IV Horn', 'Hinox Toenail',
            'Gleeok Flame Horn', 'Gleeok Frost Horn', 'Gleeok Thunder Horn', "Dinraal's Horn", "Naydra's Horn",
            "Farosh's Horn", "Light Dragon's Horn", 'Like Like Stone', 'Fire Like Stone', 'Ice Like Stone',
            'Shock Like Stone', 'Moblin Horn', 'Blue Moblin Horn', 'Black Moblin Horn', 'Silver Moblin Horn',
            'Horriblin Horn', 'Blue Horriblin Horn', 'Black Horriblin Horn', 'Silver Horriblin Horn', 'Lynel Hoof',
            'Lynel Mace Horn', 'Blue-Maned Lynel Mace Horn', 'White-Maned Lynel Mace Horn', 'Silver Lynel Mace Horn',
            'Hinox Horn', 'Blue Hinox Horn', 'Black Hinox Horn', 'Stalnox Horn', 'Molduga Jaw', 'Frox Fang',
            'Obsidian Frox Fang', 'Blue-White Frox Fang', "Shard of Dinraal's Spike", "Shard of Naydra's Spike",
            "Shard of Farosh's Spike", "Shard of Light Dragon's Spike", 'Lizalfos Tail', 'Blue Lizalfos Tail',
            'Black Lizalfos Tail', 'Silver Lizalfos Tail', 'Fire-Breath Lizalfos Tail', 'Ice-Breath Lizalfos Tail',
            'Electric Lizalfos Tail', 'Gibdo Bone', 'Octorok Tentacle', 'Bokoblin Fang', 'Moblin Fang',
            'Boss Bokoblin Fang', 'Hinox Tooth', 'Horriblin Claw', 'Lizalfos Talon', 'Frox Fingernail',
            "Dinraal's Scale", "Naydra's Scale", "Farosh's Scale", "Light Dragon's Scale", "Dinraal's Claw",
            "Naydra's Claw", "Farosh's Claw", "Light Dragon's Talon", "Shard of Dinraal's Fang",
            "Shard of Naydra's Fang", "Shard of Farosh's Fang", "Shard of Light Dragon's Fang", 'Ancient Blade',
            "King's Scale", 'Brightbloom Seed', 'Giant Brightbloom Seed', 'Hylian Pine Cone', 'Wood', 'Zonaite',
            'Large Zonaite', 'Zonai Charge', 'Large Zonai Charge']
    ActorName = ['Item_Fruit_P', 'Item_Fruit_G', 'Item_Fruit_M', 'Item_Fruit_A', 'Item_Fruit_B', 'Item_Fruit_C',
                 'Item_Fruit_E', 'Item_Fruit_F', 'Item_Fruit_H', 'Item_Fruit_I', 'FireFruit', 'IceFruit',
                 'ElectricalFruit', 'WaterFruit', 'LightFruit', 'BombFruit', 'SmokeFruit', 'ConfusionFruit',
                 'Item_Mushroom_N', 'Item_Mushroom_F', 'Item_Mushroom_O', 'Item_MushroomGet_D', 'Item_MushroomGet_K',
                 'Item_Mushroom_A', 'Item_Mushroom_B', 'Item_Mushroom_C', 'Item_Mushroom_E', 'Item_Mushroom_H',
                 'Item_Mushroom_J', 'Item_Mushroom_L', 'Item_Mushroom_M', 'Item_Mushroom_P', 'Item_PlantGet_C',
                 'Item_PlantGet_B', 'Item_PlantGet_Q', 'Item_PlantGet_A', 'Item_PlantGet_J', 'Item_Fruit_J',
                 'Item_Fruit_N', 'Item_PlantGet_M', 'Item_PlantGet_S', 'Item_PlantGet_U', 'Item_PlantGet_E',
                 'Item_PlantGet_F', 'Item_PlantGet_G', 'Item_PlantGet_H', 'Item_PlantGet_I', 'Item_PlantGet_L',
                 'Item_PlantGet_O', 'Item_PlantGet_R', 'Item_Meat_11', 'Item_Meat_12', 'Item_Meat_02', 'Item_Meat_07',
                 'Item_Meat_01', 'Item_Meat_06', 'BeeHome', 'Item_Material_03', 'Item_Material_04', 'Item_Material_07',
                 'Item_Material_10', 'Item_Material_05', 'Item_Fruit_K', 'Item_Fruit_L', 'Item_Material_01',
                 'Item_Material_02', 'Item_Material_06', 'Item_Material_08', 'Item_Material_09', 'Item_Material_11',
                 'Item_Ore_H', 'Item_Ore_J', 'Item_FishGet_I', 'Item_FishGet_B', 'Item_FishGet_A', 'Item_FishGet_L',
                 'Item_FishGet_C', 'Item_FishGet_J', 'Item_FishGet_D', 'Item_FishGet_X', 'Item_FishGet_E',
                 'Item_FishGet_H', 'Item_FishGet_Z', 'Item_FishGet_AA', 'Item_FishGet_AC', 'Item_FishGet_F',
                 'Item_FishGet_G', 'Item_FishGet_M', 'Item_InsectGet_K', 'Item_InsectGet_O', 'Item_InsectGet_Z',
                 'Animal_Insect_F', 'Animal_Insect_N', 'Animal_Insect_Q', 'Animal_Insect_R', 'Animal_Insect_AB',
                 'Animal_Insect_C', 'Animal_Insect_T', 'Animal_Insect_I', 'Animal_Insect_AA', 'Animal_Insect_G',
                 'Animal_Insect_P', 'Animal_Insect_E', 'Animal_Insect_AI', 'Animal_Insect_H', 'Animal_Insect_B',
                 'Animal_Insect_A', 'Animal_Insect_AG', 'Animal_Insect_M', 'Animal_Insect_S', 'Animal_Insect_X',
                 'Animal_Insect_AH', 'Item_Ore_A', 'Item_Ore_B', 'Item_Ore_C', 'Item_Ore_D', 'Item_Ore_E', 'Item_Ore_F',
                 'Item_Ore_G', 'Item_Ore_I', 'Item_Enemy_02', 'Item_Enemy_08', 'Item_Enemy_105', 'Item_Enemy_121',
                 'Item_Enemy_136', 'Item_Enemy_14', 'Item_Enemy_157', 'Item_Enemy_190', 'Item_Enemy_25',
                 'Item_Enemy_34', 'Item_Enemy_15', 'Item_Enemy_17', 'Item_Enemy_16', 'Item_Enemy_40', 'Item_Enemy_57',
                 'Item_Enemy_19', 'Item_Enemy_117', 'Item_Enemy_119', 'Item_Enemy_118', 'Item_Enemy_21',
                 'Item_Enemy_66', 'Item_Enemy_18', 'Item_Enemy_44', 'Item_Enemy_46', 'Item_Enemy_45', 'Item_Enemy_124',
                 'Item_Enemy_123', 'Item_Enemy_156', 'Item_Enemy_24', 'Item_Enemy_77', 'Item_Enemy_78', 'Item_Enemy_79',
                 'Item_Enemy_80', 'Item_Enemy_64', 'Item_Enemy_132', 'Item_Enemy_133', 'Item_Enemy_134',
                 'Item_Enemy_106', 'Item_Enemy_107', 'Item_Enemy_108', 'Item_Enemy_109', 'Item_Enemy_58',
                 'Item_Enemy_59', 'Item_Enemy_60', 'Item_Enemy_148', 'Item_Enemy_149', 'Item_Enemy_150',
                 'Item_Enemy_151', 'Item_Enemy_166', 'Item_Enemy_167', 'Item_Enemy_168', 'Item_Enemy_169',
                 'Item_Enemy_67', 'Item_Enemy_191', 'Item_Enemy_192', 'Item_Enemy_193', 'Item_Enemy_32',
                 'Item_Enemy_153', 'Item_Enemy_154', 'Item_Enemy_155', 'Item_Enemy_211', 'Item_Enemy_212',
                 'Item_Enemy_213', 'Item_Enemy_214', 'Item_Enemy_181', 'Item_Enemy_182', 'Item_Enemy_184',
                 'Item_Enemy_183', 'Item_Enemy_89', 'Item_Enemy_90', 'Item_Enemy_91', 'Item_Enemy_92', 'Item_Enemy_100',
                 'Item_Enemy_101', 'Item_Enemy_102', 'Item_Enemy_103', 'Item_Enemy_13', 'Item_Enemy_215',
                 'Item_Enemy_216', 'Item_Enemy_217', 'Item_Enemy_218', 'Item_Enemy_142', 'Item_Enemy_143',
                 'Item_Enemy_144', 'Item_Enemy_208', 'Item_Enemy_210', 'Item_Enemy_186', 'Item_Enemy_187',
                 'Item_Enemy_188', 'Item_Enemy_228', 'Item_Enemy_229', 'Item_Enemy_230', 'Item_Enemy_231',
                 'Item_Enemy_05', 'Item_Enemy_114', 'Item_Enemy_115', 'Item_Enemy_116', 'Item_Enemy_41',
                 'Item_Enemy_42', 'Item_Enemy_43', 'Item_Enemy_69', 'Item_Enemy_20', 'Item_Enemy_01', 'Item_Enemy_07',
                 'Item_Enemy_135', 'Item_Enemy_33', 'Item_Enemy_104', 'Item_Enemy_04', 'Item_Enemy_189',
                 'Item_Enemy_38', 'Item_Enemy_49', 'Item_Enemy_53', 'Item_Enemy_158', 'Item_Enemy_39', 'Item_Enemy_50',
                 'Item_Enemy_54', 'Item_Enemy_159', 'Item_Enemy_47', 'Item_Enemy_51', 'Item_Enemy_55', 'Item_Enemy_160',
                 'Item_Weapon_01', 'Item_KingScale', 'LightBall_Small', 'LightBall_Large', 'FldObj_Pinecone_A_01',
                 'Obj_FireWoodBundle', 'Item_Ore_L', 'Item_Ore_M', 'Item_Enemy_130', 'Item_Enemy_131']

    selected_option = dropdown_var.get()
    Name_index = Name.index(selected_option)
    list_for_c0 = ['b4','b8','b8','b8','b8','bc','bc','bc','bc','c0','c0','c0','c0','c4','c4','c4','c4','c8','c8','c8']
    list_for_65 = ['5c','5d','5e','5f','60','61','62','63','64','65','66','67','68','69','6a','6b','6c','6d','6e','6f']

    changes = {
        1: [
            {'search_hex': '4974656d5f4f72655f4c', 'replace_hex': ActorName[Name_index].encode().hex()},
            {'search_hex': 'c0', 'replace_hex': list_for_c0[len(ActorName[Name_index]) - 1]}
        ],
        5: [
            {'search_hex': '65', 'replace_hex': list_for_65[len(ActorName[Name_index]) - 1]}
        ]
    }

    print("Selected option:", selected_option)


    # Original hexadecimal content (replace this with your actual original content)

    if len(ActorName[Name_index]) == 1 or len(ActorName[Name_index]) == 5 or len(ActorName[Name_index]) == 9 or len(ActorName[Name_index]) == 13 or len(ActorName[Name_index]) == 17 or len(ActorName[Name_index]) == 20:
        original_hex_content = "594207001000000058000000c0000000c203000014000000260000003900000045000000436f6d6d7574617469766547726f75707300436f6d6d757461746976655573654974656d00537472696e67417272617900000000c203000014000000340000005a000000650000004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f415f3031004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f5a6f6e61755f415f3031004974656d5f4f72655f4c00c1020000000000c0d4000000010000a002000000c0010000c1000000e0000000c1010000020000c0ec000000c0020000a0a000000000000001000000"  # Replace this with your original hexadecimal content
    elif len(ActorName[Name_index]) == 2 or len(ActorName[Name_index]) == 6 or len(ActorName[Name_index]) == 10 or len(ActorName[Name_index]) == 14 or len(ActorName[Name_index]) == 18:
        original_hex_content = "594207001000000058000000c0000000c203000014000000260000003900000045000000436f6d6d7574617469766547726f75707300436f6d6d757461746976655573654974656d00537472696e67417272617900000000c203000014000000340000005a000000650000004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f415f3031004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f5a6f6e61755f415f3031004974656d5f4f72655f4c00000000c1020000000000c0d4000000010000a002000000c0010000c1000000e0000000c1010000020000c0ec000000c0020000a0a000000000000001000000"
    elif len(ActorName[Name_index]) == 3 or len(ActorName[Name_index]) == 7 or len(ActorName[Name_index]) == 11 or len(ActorName[Name_index]) == 15 or len(ActorName[Name_index]) == 19:
        original_hex_content = "594207001000000058000000c0000000c203000014000000260000003900000045000000436f6d6d7574617469766547726f75707300436f6d6d757461746976655573654974656d00537472696e67417272617900000000c203000014000000340000005a000000650000004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f415f3031004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f5a6f6e61755f415f3031004974656d5f4f72655f4c000000c1020000000000c0d4000000010000a002000000c0010000c1000000e0000000c1010000020000c0ec000000c0020000a0a000000000000001000000"
    elif len(ActorName[Name_index]) == 4 or len(ActorName[Name_index]) == 8 or len(ActorName[Name_index]) == 12 or len(ActorName[Name_index]) == 16 or len(ActorName[Name_index]) == 20:
        original_hex_content = "594207001000000058000000c0000000c203000014000000260000003900000045000000436f6d6d7574617469766547726f75707300436f6d6d757461746976655573654974656d00537472696e67417272617900000000c203000014000000340000005a000000650000004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f415f3031004173624f626a5f42616c6c6f6f6e456e76656c6f7065426173655f5a6f6e61755f415f3031004974656d5f4f72655f4c0000c1020000000000c0d4000000010000a002000000c0010000c1000000e0000000c1010000020000c0ec000000c0020000a0a000000000000001000000"



    # Effectuer les changements spécifiés dans le dictionnaire "changes"
    for iteration, change_list in changes.items():
        for change_info in change_list:
            search_hex = change_info['search_hex']
            replace_hex = change_info['replace_hex']

            # Find the starting index of the n-th occurrence of search_hex
            start_index = -1
            for i in range(iteration):
                start_index = original_hex_content.find(search_hex, start_index + 1)
                if start_index == -1:
                    print(f"Cannot find the {iteration}-th occurrence of {search_hex}.")
                    return

            # Replace the hexadecimal pattern at the specified index
            original_hex_content = original_hex_content[:start_index] + replace_hex + original_hex_content[
                                                                                      start_index + len(search_hex):]

    # Insert spaces back every 8 characters
    new_hex_content = " ".join(original_hex_content[i:i + 8] for i in range(0, len(original_hex_content), 8))

    # Remove any non-hexadecimal characters from new_hex_content
    new_hex_content = re.sub(r'[^0-9a-fA-F]', '', new_hex_content)

    print("new_hex_content:", new_hex_content)  # Add this line to check the content

    # Write the modified hexadecimal content back to the .bgyml file
    with open("romfs/GameParameter/AutoBuilderBuildingParam/Default.game__specialpower__AutoBuilderBuildingParam.bgyml",
              'wb') as file:
        file.write(bytes.fromhex(new_hex_content))

    print("File content changed successfully.")


def update_image(*args):
    selected_item = dropdown_var.get()
    if selected_item in options_images:
        image_label.config(image=options_images[selected_item])
    else:
        default_image = tk.PhotoImage(file="Images/Item_Ore_L.png")
        image_label.config(image=default_image)
        image_label.image = default_image


root = tk.Tk()
root.title("Autobuilder Material Changer")
root.configure(bg="#202123")
root.geometry("256x400")

ttk.Style().configure("TButton", background="#202123")
ttk.Style().configure("TCombobox", background="#202123")

dropdown_var = tk.StringVar(root)
dropdown_var.set("Zonaite")

options = ["Golden Apple", "Palm Fruit", "Hylian Tomato", "Apple", "Wildberry", "Voltfruit", "Fleet-Lotus Seeds",
           "Hydromelon", "Mighty Bananas", "Spicy Pepper",
           "Fire Fruit", "Ice Fruit", "Shock Fruit", "Splash Fruit", "Dazzlefruit", "Bomb Flower", "Puffshroom",
           "Muddle Bud", "Big Hearty Truffle", "Hearty Truffle",
           "Endura Shroom", "Rushroom", "Brightcap", "Stamella Shroom", "Chillshroom", "Sunshroom", "Hylian Shroom",
           "Zapshroom", "Silent Shroom", "Razorshroom",
           "Ironshroom", "Skyshroom", "Big Hearty Radish", "Hearty Radish", "Endura Carrot", "Hyrule Herb",
           "Silent Princess", "Fortified Pumpkin", "Sun Pumpkin", "Swift Carrot",
           "Stambulb", "Korok Frond", "Cool Safflina", "Warm Safflina", "Mighty Thistle", "Armoranth",
           "Blue Nightshade", "Electric Safflina", "Swift Violet", "Sundelion",
           "Raw Gourmet Meat", "Raw Whole Bird", "Raw Prime Meat", "Raw Bird Thigh", "Raw Meat", "Raw Bird Drumstick",
           "Courser Bee Honey", "Hylian Rice", "Bird Egg", "Tabantha Wheat",
           "Hateno Cheese", "Fresh Milk", "Acorn", "Chickaloo Tree Nut", "Cane Sugar", "Goron Spice", "Goat Butter",
           "Monster Extract", "Oil Jar", "Dark Clump",
           "Rock Salt", "Star Fragment", "Hearty Salmon", "Hearty Bass", "Hyrule Bass", "Staminoka Bass",
           "Chillfin Trout", "Sizzlefin Trout", "Voltfin Trout", "Stealthfin Trout",
           "Mighty Carp", "Armored Carp", "Sanke Carp", "Ancient Arowana", "Glowing Cave Fish", "Mighty Porgy",
           "Armored Porgy", "Sneaky River Snail", "Razorclaw Crab", "Ironshell Crab",
           "Bright-Eyed Crab", "Fairy", "Winterwing Butterfly", "Summerwing Butterfly", "Thunderwing Butterfly",
           "Smotherwing Butterfly", "Cold Darner", "Warm Darner", "Electric Darner", "Energetic Rhino Beetle",
           "Bladed Rhino Beetle", "Rugged Rhino Beetle", "Sunset Firefly", "Deep Firefly", "Restless Cricket",
           "Tireless Frog", "Hot-Footed Frog", "Sticky Frog", "Hearty Lizard", "Hightail Lizard",
           "Fireproof Lizard", "Sticky Lizard", "Diamond", "Ruby", "Sapphire", "Topaz", "Opal", "Amber",
           "Luminous Stone", "Flint",
           "Bokoblin Guts", "Moblin Guts", "Horriblin Guts", "Gibdo Guts", "Boss Bokoblin Guts", "Lynel Guts",
           "Gleeok Guts", "Frox Guts", "Molduga Guts", "Hinox Guts",
           "Red Chuchu Jelly", "White Chuchu Jelly", "Yellow Chuchu Jelly", "Chuchu Jelly", "Octo Balloon",
           "Keese Eyeball", "Fire Keese Eyeball", "Ice Keese Eyeball", "Electric Keese Eyeball", "Octorok Eyeball",
           "Aerocuda Eyeball", "Keese Wing", "Fire Keese Wing", "Ice Keese Wing", "Electric Keese Wing",
           "Aerocuda Wing", "Gibdo Wing", "Gleeok Wing", "Molduga Fin", "Bokoblin Horn",
           "Blue Bokoblin Horn", "Black Bokoblin Horn", "Silver Bokoblin Horn", "Boss Bokoblin Horn",
           "Blue Boss Bokoblin Horn", "Black Boss Bokoblin Horn", "Silver Boss Bokoblin Horn", "Lizalfos Horn",
           "Blue Lizalfos Horn", "Black Lizalfos Horn",
           "Silver Lizalfos Horn", "Fire-Breath Lizalfos Horn", "Ice-Breath Lizalfos Horn", "Electric Lizalfos Horn",
           "Lynel Saber Horn", "Blue-Maned Lynel Saber Horn", "White-Maned Lynel Saber Horn", "Silver Lynel Saber Horn",
           "Soldier Construct Horn", "Soldier Construct II Horn",
           "Soldier Construct III Horn", "Soldier Construct IV Horn", "Captain Construct I Horn",
           "Captain Construct II Horn", "Captain Construct III Horn", "Captain Construct IV Horn", "Hinox Toenail",
           "Gleeok Flame Horn", "Gleeok Frost Horn", "Gleeok Thunder Horn",
           "Dinraal's Horn", "Naydra's Horn", "Farosh's Horn", "Light Dragon's Horn", "Like Like Stone",
           "Fire Like Stone", "Ice Like Stone", "Shock Like Stone", "Moblin Horn", "Blue Moblin Horn",
           "Black Moblin Horn", "Silver Moblin Horn", "Horriblin Horn", "Blue Horriblin Horn", "Black Horriblin Horn",
           "Silver Horriblin Horn", "Lynel Hoof", "Lynel Mace Horn", "Blue-Maned Lynel Mace Horn",
           "White-Maned Lynel Mace Horn",
           "Silver Lynel Mace Horn", "Hinox Horn", "Blue Hinox Horn", "Black Hinox Horn", "Stalnox Horn", "Molduga Jaw",
           "Frox Fang", "Obsidian Frox Fang", "Blue-White Frox Fang", "Shard of Dinraal's Spike",
           "Shard of Naydra's Spike", "Shard of Farosh's Spike", "Shard of Light Dragon's Spike", "Lizalfos Tail",
           "Blue Lizalfos Tail", "Black Lizalfos Tail", "Silver Lizalfos Tail", "Fire-Breath Lizalfos Tail",
           "Ice-Breath Lizalfos Tail", "Electric Lizalfos Tail",
           "Gibdo Bone", "Octorok Tentacle", "Bokoblin Fang", "Moblin Fang", "Boss Bokoblin Fang", "Hinox Tooth",
           "Horriblin Claw", "Lizalfos Talon", "Frox Fingernail", "Dinraal's Scale",
           "Naydra's Scale", "Farosh's Scale", "Light Dragon's Scale", "Dinraal's Claw", "Naydra's Claw",
           "Farosh's Claw", "Light Dragon's Talon", "Shard of Dinraal's Fang", "Shard of Naydra's Fang",
           "Shard of Farosh's Fang",
           "Shard of Light Dragon's Fang", "Ancient Blade", "King's Scale", "Brightbloom Seed",
           "Giant Brightbloom Seed", "Hylian Pine Cone", "Wood", "Zonaite", "Large Zonaite", "Zonai Charge",
           "Large Zonai Charge"

           ]

option_image_paths = {'Golden Apple': 'Images/Item_Fruit_P.png',
                      'Palm Fruit': 'Images/Item_Fruit_G.png',
                      'Hylian Tomato': 'Images/Item_Fruit_M.png',
                      'Apple': 'Images/Item_Fruit_A.png',
                      'Wildberry': 'Images/Item_Fruit_B.png',
                      'Voltfruit': 'Images/Item_Fruit_C.png',
                      'Fleet-Lotus Seeds': 'Images/Item_Fruit_E.png',
                      'Hydromelon': 'Images/Item_Fruit_F.png',
                      'Mighty Bananas': 'Images/Item_Fruit_H.png',
                      'Spicy Pepper': 'Images/Item_Fruit_I.png',
                      'Fire Fruit': 'Images/FireFruit.png',
                      'Ice Fruit': 'Images/IceFruit.png',
                      'Shock Fruit': 'Images/ElectricalFruit.png',
                      'Splash Fruit': 'Images/WaterFruit.png',
                      'Dazzlefruit': 'Images/LightFruit.png',
                      'Bomb Flower': 'Images/BombFruit.png',
                      'Puffshroom': 'Images/SmokeFruit.png',
                      'Muddle Bud': 'Images/ConfusionFruit.png',
                      'Big Hearty Truffle': 'Images/Item_Mushroom_N.png',
                      'Hearty Truffle': 'Images/Item_Mushroom_F.png',
                      'Endura Shroom': 'Images/Item_Mushroom_O.png',
                      'Rushroom': 'Images/Item_MushroomGet_D.png',
                      'Brightcap': 'Images/Item_MushroomGet_K.png',
                      'Stamella Shroom': 'Images/Item_Mushroom_A.png',
                      'Chillshroom': 'Images/Item_Mushroom_B.png',
                      'Sunshroom': 'Images/Item_Mushroom_C.png',
                      'Hylian Shroom': 'Images/Item_Mushroom_E.png',
                      'Zapshroom': 'Images/Item_Mushroom_H.png',
                      'Silent Shroom': 'Images/Item_Mushroom_J.png',
                      'Razorshroom': 'Images/Item_Mushroom_L.png',
                      'Ironshroom': 'Images/Item_Mushroom_M.png',
                      'Skyshroom': 'Images/Item_Mushroom_P.png',
                      'Big Hearty Radish': 'Images/Item_PlantGet_C.png',
                      'Hearty Radish': 'Images/Item_PlantGet_B.png',
                      'Endura Carrot': 'Images/Item_PlantGet_Q.png',
                      'Hyrule Herb': 'Images/Item_PlantGet_A.png',
                      'Silent Princess': 'Images/Item_PlantGet_J.png',
                      'Fortified Pumpkin': 'Images/Item_Fruit_J.png',
                      'Sun Pumpkin': 'Images/Item_Fruit_N.png',
                      'Swift Carrot': 'Images/Item_PlantGet_M.png',
                      'Stambulb': 'Images/Item_PlantGet_S.png',
                      'Korok Frond': 'Images/Item_PlantGet_U.png',
                      'Cool Safflina': 'Images/Item_PlantGet_E.png',
                      'Warm Safflina': 'Images/Item_PlantGet_F.png',
                      'Mighty Thistle': 'Images/Item_PlantGet_G.png',
                      'Armoranth': 'Images/Item_PlantGet_H.png',
                      'Blue Nightshade': 'Images/Item_PlantGet_I.png',
                      'Electric Safflina': 'Images/Item_PlantGet_L.png',
                      'Swift Violet': 'Images/Item_PlantGet_O.png',
                      'Sundelion': 'Images/Item_PlantGet_R.png',
                      'Raw Gourmet Meat': 'Images/Item_Meat_11.png',
                      'Raw Whole Bird': 'Images/Item_Meat_12.png',
                      'Raw Prime Meat': 'Images/Item_Meat_02.png',
                      'Raw Bird Thigh': 'Images/Item_Meat_07.png',
                      'Raw Meat': 'Images/Item_Meat_01.png',
                      'Raw Bird Drumstick': 'Images/Item_Meat_06.png',
                      'Courser Bee Honey': 'Images/BeeHome.png',
                      'Hylian Rice': 'Images/Item_Material_03.png',
                      'Bird Egg': 'Images/Item_Material_04.png',
                      'Tabantha Wheat': 'Images/Item_Material_07.png',
                      'Hateno Cheese': 'Images/Item_Material_10.png',
                      'Fresh Milk': 'Images/Item_Material_05.png',
                      'Acorn': 'Images/Item_Fruit_K.png',
                      'Chickaloo Tree Nut': 'Images/Item_Fruit_L.png',
                      'Cane Sugar': 'Images/Item_Material_01.png',
                      'Goron Spice': 'Images/Item_Material_02.png',
                      'Goat Butter': 'Images/Item_Material_06.png',
                      'Monster Extract': 'Images/Item_Material_08.png',
                      'Oil Jar': 'Images/Item_Material_09.png',
                      'Dark Clump': 'Images/Item_Material_11.png',
                      'Rock Salt': 'Images/Item_Ore_H.png',
                      'Star Fragment': 'Images/Item_Ore_J.png',
                      'Hearty Salmon': 'Images/Item_FishGet_I.png',
                      'Hearty Bass': 'Images/Item_FishGet_B.png',
                      'Hyrule Bass': 'Images/Item_FishGet_A.png',
                      'Staminoka Bass': 'Images/Item_FishGet_L.png',
                      'Chillfin Trout': 'Images/Item_FishGet_C.png',
                      'Sizzlefin Trout': 'Images/Item_FishGet_J.png',
                      'Voltfin Trout': 'Images/Item_FishGet_D.png',
                      'Stealthfin Trout': 'Images/Item_FishGet_X.png',
                      'Mighty Carp': 'Images/Item_FishGet_E.png',
                      'Armored Carp': 'Images/Item_FishGet_H.png',
                      'Sanke Carp': 'Images/Item_FishGet_Z.png',
                      'Ancient Arowana': 'Images/Item_FishGet_AA.png',
                      'Glowing Cave Fish': 'Images/Item_FishGet_AC.png',
                      'Mighty Porgy': 'Images/Item_FishGet_F.png',
                      'Armored Porgy': 'Images/Item_FishGet_G.png',
                      'Sneaky River Snail': 'Images/Item_FishGet_M.png',
                      'Razorclaw Crab': 'Images/Item_InsectGet_K.png',
                      'Ironshell Crab': 'Images/Item_InsectGet_O.png',
                      'Bright-Eyed Crab': 'Images/Item_InsectGet_Z.png',
                      'Fairy': 'Images/Animal_Insect_F.png',
                      'Winterwing Butterfly': 'Images/Animal_Insect_N.png',
                      'Summerwing Butterfly': 'Images/Animal_Insect_Q.png',
                      'Thunderwing Butterfly': 'Images/Animal_Insect_R.png',
                      'Smotherwing Butterfly': 'Images/Animal_Insect_AB.png',
                      'Cold Darner': 'Images/Animal_Insect_C.png',
                      'Warm Darner': 'Images/Animal_Insect_T.png',
                      'Electric Darner': 'Images/Animal_Insect_I.png',
                      'Energetic Rhino Beetle': 'Images/Animal_Insect_AA.png',
                      'Bladed Rhino Beetle': 'Images/Animal_Insect_G.png',
                      'Rugged Rhino Beetle': 'Images/Animal_Insect_P.png',
                      'Sunset Firefly': 'Images/Animal_Insect_E.png',
                      'Deep Firefly': 'Images/Animal_Insect_AI.png',
                      'Restless Cricket': 'Images/Animal_Insect_H.png',
                      'Tireless Frog': 'Images/Animal_Insect_B.png',
                      'Hot-Footed Frog': 'Images/Animal_Insect_A.png',
                      'Sticky Frog': 'Images/Animal_Insect_AG.png',
                      'Hearty Lizard': 'Images/Animal_Insect_M.png',
                      'Hightail Lizard': 'Images/Animal_Insect_S.png',
                      'Fireproof Lizard': 'Images/Animal_Insect_X.png',
                      'Sticky Lizard': 'Images/Animal_Insect_AH.png',
                      'Diamond': 'Images/Item_Ore_A.png',
                      'Ruby': 'Images/Item_Ore_B.png',
                      'Sapphire': 'Images/Item_Ore_C.png',
                      'Topaz': 'Images/Item_Ore_D.png',
                      'Opal': 'Images/Item_Ore_E.png',
                      'Amber': 'Images/Item_Ore_F.png',
                      'Luminous Stone': 'Images/Item_Ore_G.png',
                      'Flint': 'Images/Item_Ore_I.png',
                      'Bokoblin Guts': 'Images/Item_Enemy_02.png',
                      'Moblin Guts': 'Images/Item_Enemy_08.png',
                      'Horriblin Guts': 'Images/Item_Enemy_105.png',
                      'Gibdo Guts': 'Images/Item_Enemy_121.png',
                      'Boss Bokoblin Guts': 'Images/Item_Enemy_136.png',
                      'Lynel Guts': 'Images/Item_Enemy_14.png',
                      'Gleeok Guts': 'Images/Item_Enemy_157.png',
                      'Frox Guts': 'Images/Item_Enemy_190.png',
                      'Molduga Guts': 'Images/Item_Enemy_25.png',
                      'Hinox Guts': 'Images/Item_Enemy_34.png',
                      'Red Chuchu Jelly': 'Images/Item_Enemy_15.png',
                      'White Chuchu Jelly': 'Images/Item_Enemy_17.png',
                      'Yellow Chuchu Jelly': 'Images/Item_Enemy_16.png',
                      'Chuchu Jelly': 'Images/Item_Enemy_40.png',
                      'Octo Balloon': 'Images/Item_Enemy_57.png',
                      'Keese Eyeball': 'Images/Item_Enemy_19.png',
                      'Fire Keese Eyeball': 'Images/Item_Enemy_117.png',
                      'Ice Keese Eyeball': 'Images/Item_Enemy_119.png',
                      'Electric Keese Eyeball': 'Images/Item_Enemy_118.png',
                      'Octorok Eyeball': 'Images/Item_Enemy_21.png',
                      'Aerocuda Eyeball': 'Images/Item_Enemy_66.png',
                      'Keese Wing': 'Images/Item_Enemy_18.png',
                      'Fire Keese Wing': 'Images/Item_Enemy_44.png',
                      'Ice Keese Wing': 'Images/Item_Enemy_46.png',
                      'Electric Keese Wing': 'Images/Item_Enemy_45.png',
                      'Aerocuda Wing': 'Images/Item_Enemy_124.png',
                      'Gibdo Wing': 'Images/Item_Enemy_123.png',
                      'Gleeok Wing': 'Images/Item_Enemy_156.png',
                      'Molduga Fin': 'Images/Item_Enemy_24.png',
                      'Bokoblin Horn': 'Images/Item_Enemy_77.png',
                      'Blue Bokoblin Horn': 'Images/Item_Enemy_78.png',
                      'Black Bokoblin Horn': 'Images/Item_Enemy_79.png',
                      'Silver Bokoblin Horn': 'Images/Item_Enemy_80.png',
                      'Boss Bokoblin Horn': 'Images/Item_Enemy_64.png',
                      'Blue Boss Bokoblin Horn': 'Images/Item_Enemy_132.png',
                      'Black Boss Bokoblin Horn': 'Images/Item_Enemy_133.png',
                      'Silver Boss Bokoblin Horn': 'Images/Item_Enemy_134.png',
                      'Lizalfos Horn': 'Images/Item_Enemy_106.png',
                      'Blue Lizalfos Horn': 'Images/Item_Enemy_107.png',
                      'Black Lizalfos Horn': 'Images/Item_Enemy_108.png',
                      'Silver Lizalfos Horn': 'Images/Item_Enemy_109.png',
                      'Fire-Breath Lizalfos Horn': 'Images/Item_Enemy_58.png',
                      'Ice-Breath Lizalfos Horn': 'Images/Item_Enemy_59.png',
                      'Electric Lizalfos Horn': 'Images/Item_Enemy_60.png',
                      'Lynel Saber Horn': 'Images/Item_Enemy_148.png',
                      'Blue-Maned Lynel Saber Horn': 'Images/Item_Enemy_149.png',
                      'White-Maned Lynel Saber Horn': 'Images/Item_Enemy_150.png',
                      'Silver Lynel Saber Horn': 'Images/Item_Enemy_151.png',
                      'Soldier Construct Horn': 'Images/Item_Enemy_166.png',
                      'Soldier Construct II Horn': 'Images/Item_Enemy_167.png',
                      'Soldier Construct III Horn': 'Images/Item_Enemy_168.png',
                      'Soldier Construct IV Horn': 'Images/Item_Enemy_169.png',
                      'Captain Construct I Horn': 'Images/Item_Enemy_67.png',
                      'Captain Construct II Horn': 'Images/Item_Enemy_191.png',
                      'Captain Construct III Horn': 'Images/Item_Enemy_192.png',
                      'Captain Construct IV Horn': 'Images/Item_Enemy_193.png',
                      'Hinox Toenail': 'Images/Item_Enemy_32.png',
                      'Gleeok Flame Horn': 'Images/Item_Enemy_153.png',
                      'Gleeok Frost Horn': 'Images/Item_Enemy_154.png',
                      'Gleeok Thunder Horn': 'Images/Item_Enemy_155.png',
                      "Dinraal's Horn": 'Images/Item_Enemy_211.png',
                      "Naydra's Horn": 'Images/Item_Enemy_212.png',
                      "Farosh's Horn": 'Images/Item_Enemy_213.png',
                      "Light Dragon's Horn": 'Images/Item_Enemy_214.png',
                      'Like Like Stone': 'Images/Item_Enemy_181.png',
                      'Fire Like Stone': 'Images/Item_Enemy_182.png',
                      'Ice Like Stone': 'Images/Item_Enemy_184.png',
                      'Shock Like Stone': 'Images/Item_Enemy_183.png',
                      'Moblin Horn': 'Images/Item_Enemy_89.png',
                      'Blue Moblin Horn': 'Images/Item_Enemy_90.png',
                      'Black Moblin Horn': 'Images/Item_Enemy_91.png',
                      'Silver Moblin Horn': 'Images/Item_Enemy_92.png',
                      'Horriblin Horn': 'Images/Item_Enemy_100.png',
                      'Blue Horriblin Horn': 'Images/Item_Enemy_101.png',
                      'Black Horriblin Horn': 'Images/Item_Enemy_102.png',
                      'Silver Horriblin Horn': 'Images/Item_Enemy_103.png',
                      'Lynel Hoof': 'Images/Item_Enemy_13.png',
                      'Lynel Mace Horn': 'Images/Item_Enemy_215.png',
                      'Blue-Maned Lynel Mace Horn': 'Images/Item_Enemy_216.png',
                      'White-Maned Lynel Mace Horn': 'Images/Item_Enemy_217.png',
                      'Silver Lynel Mace Horn': 'Images/Item_Enemy_218.png',
                      'Hinox Horn': 'Images/Item_Enemy_142.png',
                      'Blue Hinox Horn': 'Images/Item_Enemy_143.png',
                      'Black Hinox Horn': 'Images/Item_Enemy_144.png',
                      'Stalnox Horn': 'Images/Item_Enemy_208.png',
                      'Molduga Jaw': 'Images/Item_Enemy_210.png',
                      'Frox Fang': 'Images/Item_Enemy_186.png',
                      'Obsidian Frox Fang': 'Images/Item_Enemy_187.png',
                      'Blue-White Frox Fang': 'Images/Item_Enemy_188.png',
                      "Shard of Dinraal's Spike": 'Images/Item_Enemy_228.png',
                      "Shard of Naydra's Spike": 'Images/Item_Enemy_229.png',
                      "Shard of Farosh's Spike": 'Images/Item_Enemy_230.png',
                      "Shard of Light Dragon's Spike": 'Images/Item_Enemy_231.png',
                      'Lizalfos Tail': 'Images/Item_Enemy_05.png',
                      'Blue Lizalfos Tail': 'Images/Item_Enemy_114.png',
                      'Black Lizalfos Tail': 'Images/Item_Enemy_115.png',
                      'Silver Lizalfos Tail': 'Images/Item_Enemy_116.png',
                      'Fire-Breath Lizalfos Tail': 'Images/Item_Enemy_41.png',
                      'Ice-Breath Lizalfos Tail': 'Images/Item_Enemy_42.png',
                      'Electric Lizalfos Tail': 'Images/Item_Enemy_43.png',
                      'Gibdo Bone': 'Images/Item_Enemy_69.png',
                      'Octorok Tentacle': 'Images/Item_Enemy_20.png',
                      'Bokoblin Fang': 'Images/Item_Enemy_01.png',
                      'Moblin Fang': 'Images/Item_Enemy_07.png',
                      'Boss Bokoblin Fang': 'Images/Item_Enemy_135.png',
                      'Hinox Tooth': 'Images/Item_Enemy_33.png',
                      'Horriblin Claw': 'Images/Item_Enemy_104.png',
                      'Lizalfos Talon': 'Images/Item_Enemy_04.png',
                      'Frox Fingernail': 'Images/Item_Enemy_189.png',
                      "Dinraal's Scale": 'Images/Item_Enemy_38.png',
                      "Naydra's Scale": 'Images/Item_Enemy_49.png',
                      "Farosh's Scale": 'Images/Item_Enemy_53.png',
                      "Light Dragon's Scale": 'Images/Item_Enemy_158.png',
                      "Dinraal's Claw": 'Images/Item_Enemy_39.png',
                      "Naydra's Claw": 'Images/Item_Enemy_50.png',
                      "Farosh's Claw": 'Images/Item_Enemy_54.png',
                      "Light Dragon's Talon": 'Images/Item_Enemy_159.png',
                      "Shard of Dinraal's Fang": 'Images/Item_Enemy_47.png',
                      "Shard of Naydra's Fang": 'Images/Item_Enemy_51.png',
                      "Shard of Farosh's Fang": 'Images/Item_Enemy_55.png',
                      "Shard of Light Dragon's Fang": 'Images/Item_Enemy_160.png',
                      'Ancient Blade': 'Images/Item_Weapon_01.png',
                      "King's Scale": 'Images/Item_KingScale.png',
                      'Brightbloom Seed': 'Images/LightBall_Small.png',
                      'Giant Brightbloom Seed': 'Images/LightBall_Large.png',
                      'Hylian Pine Cone': 'Images/FldObj_Pinecone_A_01.png',
                      'Wood': 'Images/Obj_FireWoodBundle.png',
                      'Zonaite': 'Images/Item_Ore_L.png',
                      'Large Zonaite': 'Images/Item_Ore_M.png',
                      'Zonai Charge': 'Images/Item_Enemy_130.png',
                      'Large Zonai Charge': 'Images/Item_Enemy_131.png'
                      }

little_image_paths = {'Golden Apple': 'Images/Item_Fruit_P.png',
                      'Palm Fruit': 'Images/Item_Fruit_G.png',
                      'Hylian Tomato': 'Images/Item_Fruit_M.png',
                      'Apple': 'Images/Item_Fruit_A.png',
                      'Wildberry': 'Images/Item_Fruit_B.png',
                      'Voltfruit': 'Images/Item_Fruit_C.png',
                      'Fleet-Lotus Seeds': 'Images/Item_Fruit_E.png',
                      'Hydromelon': 'Images/Item_Fruit_F.png',
                      'Mighty Bananas': 'Images/Item_Fruit_H.png',
                      'Spicy Pepper': 'Images/Item_Fruit_I.png',
                      'Fire Fruit': 'Images/FireFruit.png',
                      'Ice Fruit': 'Images/IceFruit.png',
                      'Shock Fruit': 'Images/ElectricalFruit.png',
                      'Splash Fruit': 'Images/WaterFruit.png',
                      'Dazzlefruit': 'Images/LightFruit.png',
                      'Bomb Flower': 'Images/BombFruit.png',
                      'Puffshroom': 'Images/SmokeFruit.png',
                      'Muddle Bud': 'Images/ConfusionFruit.png',
                      'Big Hearty Truffle': 'Images/Item_Mushroom_N.png',
                      'Hearty Truffle': 'Images/Item_Mushroom_F.png',
                      'Endura Shroom': 'Images/Item_Mushroom_O.png',
                      'Rushroom': 'Images/Item_MushroomGet_D.png',
                      'Brightcap': 'Images/Item_MushroomGet_K.png',
                      'Stamella Shroom': 'Images/Item_Mushroom_A.png',
                      'Chillshroom': 'Images/Item_Mushroom_B.png',
                      'Sunshroom': 'Images/Item_Mushroom_C.png',
                      'Hylian Shroom': 'Images/Item_Mushroom_E.png',
                      'Zapshroom': 'Images/Item_Mushroom_H.png',
                      'Silent Shroom': 'Images/Item_Mushroom_J.png',
                      'Razorshroom': 'Images/Item_Mushroom_L.png',
                      'Ironshroom': 'Images/Item_Mushroom_M.png',
                      'Skyshroom': 'Images/Item_Mushroom_P.png',
                      'Big Hearty Radish': 'Images/Item_PlantGet_C.png',
                      'Hearty Radish': 'Images/Item_PlantGet_B.png',
                      'Endura Carrot': 'Images/Item_PlantGet_Q.png',
                      'Hyrule Herb': 'Images/Item_PlantGet_A.png',
                      'Silent Princess': 'Images/Item_PlantGet_J.png',
                      'Fortified Pumpkin': 'Images/Item_Fruit_J.png',
                      'Sun Pumpkin': 'Images/Item_Fruit_N.png',
                      'Swift Carrot': 'Images/Item_PlantGet_M.png',
                      'Stambulb': 'Images/Item_PlantGet_S.png',
                      'Korok Frond': 'Images/Item_PlantGet_U.png',
                      'Cool Safflina': 'Images/Item_PlantGet_E.png',
                      'Warm Safflina': 'Images/Item_PlantGet_F.png',
                      'Mighty Thistle': 'Images/Item_PlantGet_G.png',
                      'Armoranth': 'Images/Item_PlantGet_H.png',
                      'Blue Nightshade': 'Images/Item_PlantGet_I.png',
                      'Electric Safflina': 'Images/Item_PlantGet_L.png',
                      'Swift Violet': 'Images/Item_PlantGet_O.png',
                      'Sundelion': 'Images/Item_PlantGet_R.png',
                      'Raw Gourmet Meat': 'Images/Item_Meat_11.png',
                      'Raw Whole Bird': 'Images/Item_Meat_12.png',
                      'Raw Prime Meat': 'Images/Item_Meat_02.png',
                      'Raw Bird Thigh': 'Images/Item_Meat_07.png',
                      'Raw Meat': 'Images/Item_Meat_01.png',
                      'Raw Bird Drumstick': 'Images/Item_Meat_06.png',
                      'Courser Bee Honey': 'Images/BeeHome.png',
                      'Hylian Rice': 'Images/Item_Material_03.png',
                      'Bird Egg': 'Images/Item_Material_04.png',
                      'Tabantha Wheat': 'Images/Item_Material_07.png',
                      'Hateno Cheese': 'Images/Item_Material_10.png',
                      'Fresh Milk': 'Images/Item_Material_05.png',
                      'Acorn': 'Images/Item_Fruit_K.png',
                      'Chickaloo Tree Nut': 'Images/Item_Fruit_L.png',
                      'Cane Sugar': 'Images/Item_Material_01.png',
                      'Goron Spice': 'Images/Item_Material_02.png',
                      'Goat Butter': 'Images/Item_Material_06.png',
                      'Monster Extract': 'Images/Item_Material_08.png',
                      'Oil Jar': 'Images/Item_Material_09.png',
                      'Dark Clump': 'Images/Item_Material_11.png',
                      'Rock Salt': 'Images/Item_Ore_H.png',
                      'Star Fragment': 'Images/Item_Ore_J.png',
                      'Hearty Salmon': 'Images/Item_FishGet_I.png',
                      'Hearty Bass': 'Images/Item_FishGet_B.png',
                      'Hyrule Bass': 'Images/Item_FishGet_A.png',
                      'Staminoka Bass': 'Images/Item_FishGet_L.png',
                      'Chillfin Trout': 'Images/Item_FishGet_C.png',
                      'Sizzlefin Trout': 'Images/Item_FishGet_J.png',
                      'Voltfin Trout': 'Images/Item_FishGet_D.png',
                      'Stealthfin Trout': 'Images/Item_FishGet_X.png',
                      'Mighty Carp': 'Images/Item_FishGet_E.png',
                      'Armored Carp': 'Images/Item_FishGet_H.png',
                      'Sanke Carp': 'Images/Item_FishGet_Z.png',
                      'Ancient Arowana': 'Images/Item_FishGet_AA.png',
                      'Glowing Cave Fish': 'Images/Item_FishGet_AC.png',
                      'Mighty Porgy': 'Images/Item_FishGet_F.png',
                      'Armored Porgy': 'Images/Item_FishGet_G.png',
                      'Sneaky River Snail': 'Images/Item_FishGet_M.png',
                      'Razorclaw Crab': 'Images/Item_InsectGet_K.png',
                      'Ironshell Crab': 'Images/Item_InsectGet_O.png',
                      'Bright-Eyed Crab': 'Images/Item_InsectGet_Z.png',
                      'Fairy': 'Images/Animal_Insect_F.png',
                      'Winterwing Butterfly': 'Images/Animal_Insect_N.png',
                      'Summerwing Butterfly': 'Images/Animal_Insect_Q.png',
                      'Thunderwing Butterfly': 'Images/Animal_Insect_R.png',
                      'Smotherwing Butterfly': 'Images/Animal_Insect_AB.png',
                      'Cold Darner': 'Images/Animal_Insect_C.png',
                      'Warm Darner': 'Images/Animal_Insect_T.png',
                      'Electric Darner': 'Images/Animal_Insect_I.png',
                      'Energetic Rhino Beetle': 'Images/Animal_Insect_AA.png',
                      'Bladed Rhino Beetle': 'Images/Animal_Insect_G.png',
                      'Rugged Rhino Beetle': 'Images/Animal_Insect_P.png',
                      'Sunset Firefly': 'Images/Animal_Insect_E.png',
                      'Deep Firefly': 'Images/Animal_Insect_AI.png',
                      'Restless Cricket': 'Images/Animal_Insect_H.png',
                      'Tireless Frog': 'Images/Animal_Insect_B.png',
                      'Hot-Footed Frog': 'Images/Animal_Insect_A.png',
                      'Sticky Frog': 'Images/Animal_Insect_AG.png',
                      'Hearty Lizard': 'Images/Animal_Insect_M.png',
                      'Hightail Lizard': 'Images/Animal_Insect_S.png',
                      'Fireproof Lizard': 'Images/Animal_Insect_X.png',
                      'Sticky Lizard': 'Images/Animal_Insect_AH.png',
                      'Diamond': 'Images/Item_Ore_A.png',
                      'Ruby': 'Images/Item_Ore_B.png',
                      'Sapphire': 'Images/Item_Ore_C.png',
                      'Topaz': 'Images/Item_Ore_D.png',
                      'Opal': 'Images/Item_Ore_E.png',
                      'Amber': 'Images/Item_Ore_F.png',
                      'Luminous Stone': 'Images/Item_Ore_G.png',
                      'Flint': 'Images/Item_Ore_I.png',
                      'Bokoblin Guts': 'Images/Item_Enemy_02.png',
                      'Moblin Guts': 'Images/Item_Enemy_08.png',
                      'Horriblin Guts': 'Images/Item_Enemy_105.png',
                      'Gibdo Guts': 'Images/Item_Enemy_121.png',
                      'Boss Bokoblin Guts': 'Images/Item_Enemy_136.png',
                      'Lynel Guts': 'Images/Item_Enemy_14.png',
                      'Gleeok Guts': 'Images/Item_Enemy_157.png',
                      'Frox Guts': 'Images/Item_Enemy_190.png',
                      'Molduga Guts': 'Images/Item_Enemy_25.png',
                      'Hinox Guts': 'Images/Item_Enemy_34.png',
                      'Red Chuchu Jelly': 'Images/Item_Enemy_15.png',
                      'White Chuchu Jelly': 'Images/Item_Enemy_17.png',
                      'Yellow Chuchu Jelly': 'Images/Item_Enemy_16.png',
                      'Chuchu Jelly': 'Images/Item_Enemy_40.png',
                      'Octo Balloon': 'Images/Item_Enemy_57.png',
                      'Keese Eyeball': 'Images/Item_Enemy_19.png',
                      'Fire Keese Eyeball': 'Images/Item_Enemy_117.png',
                      'Ice Keese Eyeball': 'Images/Item_Enemy_119.png',
                      'Electric Keese Eyeball': 'Images/Item_Enemy_118.png',
                      'Octorok Eyeball': 'Images/Item_Enemy_21.png',
                      'Aerocuda Eyeball': 'Images/Item_Enemy_66.png',
                      'Keese Wing': 'Images/Item_Enemy_18.png',
                      'Fire Keese Wing': 'Images/Item_Enemy_44.png',
                      'Ice Keese Wing': 'Images/Item_Enemy_46.png',
                      'Electric Keese Wing': 'Images/Item_Enemy_45.png',
                      'Aerocuda Wing': 'Images/Item_Enemy_124.png',
                      'Gibdo Wing': 'Images/Item_Enemy_123.png',
                      'Gleeok Wing': 'Images/Item_Enemy_156.png',
                      'Molduga Fin': 'Images/Item_Enemy_24.png',
                      'Bokoblin Horn': 'Images/Item_Enemy_77.png',
                      'Blue Bokoblin Horn': 'Images/Item_Enemy_78.png',
                      'Black Bokoblin Horn': 'Images/Item_Enemy_79.png',
                      'Silver Bokoblin Horn': 'Images/Item_Enemy_80.png',
                      'Boss Bokoblin Horn': 'Images/Item_Enemy_64.png',
                      'Blue Boss Bokoblin Horn': 'Images/Item_Enemy_132.png',
                      'Black Boss Bokoblin Horn': 'Images/Item_Enemy_133.png',
                      'Silver Boss Bokoblin Horn': 'Images/Item_Enemy_134.png',
                      'Lizalfos Horn': 'Images/Item_Enemy_106.png',
                      'Blue Lizalfos Horn': 'Images/Item_Enemy_107.png',
                      'Black Lizalfos Horn': 'Images/Item_Enemy_108.png',
                      'Silver Lizalfos Horn': 'Images/Item_Enemy_109.png',
                      'Fire-Breath Lizalfos Horn': 'Images/Item_Enemy_58.png',
                      'Ice-Breath Lizalfos Horn': 'Images/Item_Enemy_59.png',
                      'Electric Lizalfos Horn': 'Images/Item_Enemy_60.png',
                      'Lynel Saber Horn': 'Images/Item_Enemy_148.png',
                      'Blue-Maned Lynel Saber Horn': 'Images/Item_Enemy_149.png',
                      'White-Maned Lynel Saber Horn': 'Images/Item_Enemy_150.png',
                      'Silver Lynel Saber Horn': 'Images/Item_Enemy_151.png',
                      'Soldier Construct Horn': 'Images/Item_Enemy_166.png',
                      'Soldier Construct II Horn': 'Images/Item_Enemy_167.png',
                      'Soldier Construct III Horn': 'Images/Item_Enemy_168.png',
                      'Soldier Construct IV Horn': 'Images/Item_Enemy_169.png',
                      'Captain Construct I Horn': 'Images/Item_Enemy_67.png',
                      'Captain Construct II Horn': 'Images/Item_Enemy_191.png',
                      'Captain Construct III Horn': 'Images/Item_Enemy_192.png',
                      'Captain Construct IV Horn': 'Images/Item_Enemy_193.png',
                      'Hinox Toenail': 'Images/Item_Enemy_32.png',
                      'Gleeok Flame Horn': 'Images/Item_Enemy_153.png',
                      'Gleeok Frost Horn': 'Images/Item_Enemy_154.png',
                      'Gleeok Thunder Horn': 'Images/Item_Enemy_155.png',
                      "Dinraal's Horn": 'Images/Item_Enemy_211.png',
                      "Naydra's Horn": 'Images/Item_Enemy_212.png',
                      "Farosh's Horn": 'Images/Item_Enemy_213.png',
                      "Light Dragon's Horn": 'Images/Item_Enemy_214.png',
                      'Like Like Stone': 'Images/Item_Enemy_181.png',
                      'Fire Like Stone': 'Images/Item_Enemy_182.png',
                      'Ice Like Stone': 'Images/Item_Enemy_184.png',
                      'Shock Like Stone': 'Images/Item_Enemy_183.png',
                      'Moblin Horn': 'Images/Item_Enemy_89.png',
                      'Blue Moblin Horn': 'Images/Item_Enemy_90.png',
                      'Black Moblin Horn': 'Images/Item_Enemy_91.png',
                      'Silver Moblin Horn': 'Images/Item_Enemy_92.png',
                      'Horriblin Horn': 'Images/Item_Enemy_100.png',
                      'Blue Horriblin Horn': 'Images/Item_Enemy_101.png',
                      'Black Horriblin Horn': 'Images/Item_Enemy_102.png',
                      'Silver Horriblin Horn': 'Images/Item_Enemy_103.png',
                      'Lynel Hoof': 'Images/Item_Enemy_13.png',
                      'Lynel Mace Horn': 'Images/Item_Enemy_215.png',
                      'Blue-Maned Lynel Mace Horn': 'Images/Item_Enemy_216.png',
                      'White-Maned Lynel Mace Horn': 'Images/Item_Enemy_217.png',
                      'Silver Lynel Mace Horn': 'Images/Item_Enemy_218.png',
                      'Hinox Horn': 'Images/Item_Enemy_142.png',
                      'Blue Hinox Horn': 'Images/Item_Enemy_143.png',
                      'Black Hinox Horn': 'Images/Item_Enemy_144.png',
                      'Stalnox Horn': 'Images/Item_Enemy_208.png',
                      'Molduga Jaw': 'Images/Item_Enemy_210.png',
                      'Frox Fang': 'Images/Item_Enemy_186.png',
                      'Obsidian Frox Fang': 'Images/Item_Enemy_187.png',
                      'Blue-White Frox Fang': 'Images/Item_Enemy_188.png',
                      "Shard of Dinraal's Spike": 'Images/Item_Enemy_228.png',
                      "Shard of Naydra's Spike": 'Images/Item_Enemy_229.png',
                      "Shard of Farosh's Spike": 'Images/Item_Enemy_230.png',
                      "Shard of Light Dragon's Spike": 'Images/Item_Enemy_231.png',
                      'Lizalfos Tail': 'Images/Item_Enemy_05.png',
                      'Blue Lizalfos Tail': 'Images/Item_Enemy_114.png',
                      'Black Lizalfos Tail': 'Images/Item_Enemy_115.png',
                      'Silver Lizalfos Tail': 'Images/Item_Enemy_116.png',
                      'Fire-Breath Lizalfos Tail': 'Images/Item_Enemy_41.png',
                      'Ice-Breath Lizalfos Tail': 'Images/Item_Enemy_42.png',
                      'Electric Lizalfos Tail': 'Images/Item_Enemy_43.png',
                      'Gibdo Bone': 'Images/Item_Enemy_69.png',
                      'Octorok Tentacle': 'Images/Item_Enemy_20.png',
                      'Bokoblin Fang': 'Images/Item_Enemy_01.png',
                      'Moblin Fang': 'Images/Item_Enemy_07.png',
                      'Boss Bokoblin Fang': 'Images/Item_Enemy_135.png',
                      'Hinox Tooth': 'Images/Item_Enemy_33.png',
                      'Horriblin Claw': 'Images/Item_Enemy_104.png',
                      'Lizalfos Talon': 'Images/Item_Enemy_04.png',
                      'Frox Fingernail': 'Images/Item_Enemy_189.png',
                      "Dinraal's Scale": 'Images/Item_Enemy_38.png',
                      "Naydra's Scale": 'Images/Item_Enemy_49.png',
                      "Farosh's Scale": 'Images/Item_Enemy_53.png',
                      "Light Dragon's Scale": 'Images/Item_Enemy_158.png',
                      "Dinraal's Claw": 'Images/Item_Enemy_39.png',
                      "Naydra's Claw": 'Images/Item_Enemy_50.png',
                      "Farosh's Claw": 'Images/Item_Enemy_54.png',
                      "Light Dragon's Talon": 'Images/Item_Enemy_159.png',
                      "Shard of Dinraal's Fang": 'Images/Item_Enemy_47.png',
                      "Shard of Naydra's Fang": 'Images/Item_Enemy_51.png',
                      "Shard of Farosh's Fang": 'Images/Item_Enemy_55.png',
                      "Shard of Light Dragon's Fang": 'Images/Item_Enemy_160.png',
                      'Ancient Blade': 'Images/Item_Weapon_01.png',
                      "King's Scale": 'Images/Item_KingScale.png',
                      'Brightbloom Seed': 'Images/LightBall_Small.png',
                      'Giant Brightbloom Seed': 'Images/LightBall_Large.png',
                      'Hylian Pine Cone': 'Images/FldObj_Pinecone_A_01.png',
                      'Wood': 'Images/Obj_FireWoodBundle.png',
                      'Zonaite': 'Images/Item_Ore_L.png',
                      'Large Zonaite': 'Images/Item_Ore_M.png',
                      'Zonai Charge': 'Images/Item_Enemy_130.png',
                      'Large Zonai Charge': 'Images/Item_Enemy_131.png'
                      }

options_images = {}
for option, image_path in option_image_paths.items():
    image = Image.open(image_path)
    options_images[option] = ImageTk.PhotoImage(image)

image_label = tk.Label(root, highlightthickness=0, bd=0)
image_label.pack(pady=10)
update_image()

save_button = tk.Button(root, text="Save", command=save_data, bg="#202123", fg="#bdbecd")
save_button.pack(pady=10)


def set_compound_image(option_menu, options, little_images):
    for option in options:
        image = Image.open(little_images[option])
        image = image.resize((30, 30))
        little_image = ImageTk.PhotoImage(image)
        option_menu["menu"].entryconfig(option, image=little_image, compound="right", background="#202123",
                                        foreground="#bdbecd")
        option_menu.image_references.append(little_image)


dropdown_menu = tk.OptionMenu(root, dropdown_var, *options, command=update_image)
dropdown_menu.image_references = []
set_compound_image(dropdown_menu, options, little_image_paths)

dropdown_menu.config(bg="#202123", fg="#bdbecd", activebackground="#202123", activeforeground="#bdbecd",
                     highlightthickness=0)
dropdown_menu.pack(pady=20)

root.mainloop()
